### ISSUE TITLE
比它快几倍？怎么得出来的，真的假的？

### ISSUE THREAD

**Issue by ndj888** [bupt1987/html-parser#10]

**Comment by bupt1987** [comment]
自己测试的。你可以试试。

**Comment by shinbonlin** [comment]
你可以自己試看看, 讀一個 100kb 的網頁文件, 頁首設時間, 頁尾設時間, 中間迴圈 10萬次, 去看完成時間, 我比較過這個版本和原本的 php simple dom, 這個速度快了10 倍有, 所以我現在改用這個, 也感謝 bupt1987改寫這個版本~ 如果可以和完全支援原本的 php simple dom 使用方法就更好了. 我剛 push 一個 pull , 加入一個支援原本特色的用法, plaintext, innertext  和 outertext 可以整合進版本

**Comment by phoenixbird** [comment]
直接 new \HtmlParser\ParserDom($html);会报错啊

**Comment by shinbonlin** [comment]
你使用的 phpFramework 載入 library的方式不支持 namespace 的話
把第二行註釋掉, 然後
new ParserDom($html);  即可
