### ISSUE TITLE
请问一下 这个类库可直接替换simple html dom parser 类库吗

### ISSUE THREAD

**Issue by sursir** [bupt1987/html-parser#20]
我想直接用这个类库替换 simple html dom parser 类库，
这个类库是否实现了simple htmldom parser 中的所有方法

请问是否可行呢

**Comment by bupt1987** [comment]
不确定100%兼容, 最好自己测试下

**Comment by sursir** [comment]
Thanks :)

2017-05-05 14:56 GMT+08:00 俊杰jerry <notifications@github.com<mailto:notifications@github.com>>:

Closed #20<https://github.com/bupt1987/html-parser/issues/20>.
