### ISSUE TITLE
解析获取内容，显示错误

### ISSUE THREAD

**Issue by lovesuzhou** [bupt1987/html-parser#21]
//简介内容
    $desc = $jianDom->find('div.jianji');
    //作者名字
    $authorName = $jianDom->find('div.title',0);

    echo $desc[0]->innerHtml(). "\n". $authorName->innerHtml()."\n";

显示的内容，跟网页上的不一样。

很奇怪。。。。。估计是编码问题。。。。期待解决回复。

谢谢

**Comment by bupt1987** [comment]
readme里面有写

注意：html代码必须是utf-8编码字符，如果不是请转成utf-8
如果有乱码的问题参考：http://www.fwolf.com/blog/post/314
