### ISSUE TITLE
所需的php最低版本是多少？

### ISSUE THREAD

**Issue by iyaozhen** [bupt1987/html-parser#3]
我看见composer.json里面有说明"php": ">=5.4.0"。我生产环境的php版本是：PHP 5.3.10。我在使用你以前的HtmlParserModel没什么问题。不知道能否直接使用你现在的版本？

**Comment by bupt1987** [comment]
应该可以 php >= 5.3.2 应该没问题,我改下

**Comment by iyaozhen** [comment]
嗯，谢谢。这个库很给力。(^_^)来自我的华为手机-------- 原始邮件 --------主题：Re: [html-parser] 所需的php最低版本是多少？ (#3)发件人：俊杰jerry 收件人：bupt1987/html-parser 抄送：姚振 应该可以 php >= 5.3.2 应该没问题,我改下
