### ISSUE TITLE
可否增加获取标签对内容的功能？

### ISSUE THREAD

**Issue by qizhihere** [bupt1987/html-parser#5]
做html解析挺好用的，可否考虑一下增加提取内容、属性值的功能？

**Comment by bupt1987** [comment]
什么意思，现在有 
$p1->getAttr('class'); 
这样的方式来取属性的值

**Comment by qizhihere** [comment]
比如
```html
<h2>标题</h2>
```
可否直接提取其中的`标题`？
又或者
```html
<div><span>文本</span></div>
```
可否提取其中的`<span>文本</span>`？

**Comment by qizhihere** [comment]
抱歉，我太粗心了，没有注意看。
$div->getPlainText();
不好意思哈，可以关闭这个issue了

**Comment by qizhihere** [comment]
抱歉，我太粗心了，没有注意看。
$div->getPlainText();
不好意思哈，可以关闭这个issue了
