### ISSUE TITLE
你好，请问2.1版本是稳定版吗

### ISSUE THREAD

**Issue by Lagolas** [bupt1987/html-parser#7]
你好，请问2.1版本是稳定版吗？谢谢

**Comment by Lagolas** [comment]
autoload.php在哪里呢？谢谢

**Comment by bupt1987** [comment]
你先安装 composer ,然后看下这个工具怎么用, 地址: https://getcomposer.org/

**Comment by Lagolas** [comment]
好的，谢谢

**Comment by Lagolas** [comment]
你好，我在执行find方法的时候，发现获取选择器的内容的同时，内容中的html标签（例如文章中的段落<p>）被过滤掉了，有什么设置，可以保存内容中的标签吗

**Comment by bupt1987** [comment]
没有很好的办法, 你可以子集解析下..例如:

$html_dom = new \HtmlParser\ParserDom($html);
$div = $html_dom->find('div#test1',0);
echo print_node($div->node) . "\n";

function print_node(\DOMNode $oNode) {
	if($oNode->hasChildNodes()) {
		$sHtml = '';
		foreach($oNode->childNodes as $oChild) {
			if($oChild instanceof \DOMElement) {
				$sHtml .= '<' . $oChild->tagName;
				if($oChild->tagName === 'br') {
					$sHtml .= '/>';
				} else {
					foreach($oChild->attributes as $name => $oAttr) {
						$sHtml .= ' ' . $name . '="' . $oAttr->nodeValue . '"';
					}
					if($oChild->tagName === 'input') {
						$sHtml .= '/>';
					} else {
						$sHtml .= '>';
						$sHtml .= print_node($oChild);
						$sHtml .= '</' . $oChild->tagName . '>';
					}
				}
			} else {
				$sHtml .= $oChild->nodeValue;
			}
		}
	} else {
		$sHtml = $oNode->nodeValue;
	}
	return $sHtml;
}

**Comment by bupt1987** [comment]
最新版本的加入了 innerHtml 和 outerHtml 方法, 可以获取里面html代码

**Comment by Lagolas** [comment]
好的，我看下，谢谢，你刚才那个方法不可以获取
现在我用你的最新版看一下

**Comment by Lagolas** [comment]
这个2.2版本的parsedom没有加载另外两个文件

**Comment by Lagolas** [comment]
![qq 20150610182141](https://cloud.githubusercontent.com/assets/11456016/8080314/15cc2f8c-0f9e-11e5-8f23-1b055eecc8a2.png)
可以获取到了，谢谢
请问这个ParserDom不用去继承另外那两个类了吗

**Comment by bupt1987** [comment]
不用了,我合到一个文件里面了

**Comment by Lagolas** [comment]
好的，谢谢
