### ISSUE TITLE
你好，用outerHtml()取出来的字符编码为什么是Unicode

### ISSUE THREAD

**Issue by Lagolas** [bupt1987/html-parser#8]
你好，用outerHtml()取出来的字符编码为什么是Unicode

\&#39318;\&#26399;\&#39044;\&#21578;\&#65306;\&#22899;\&#31070;\&#25340;\&#20102;\&#65281;\&#33539;\&#20912;\&#20912;
用innerHtml取出来的就是正常的文字呢
谢谢

**Comment by bupt1987** [comment]
最新master分支已经修复了这个问题

**Comment by Lagolas** [comment]
好的，谢谢你
